### ISSUE TITLE
无法复制神秘代码

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaCopilotDesigner#3]
提示已复制，但实际上并没有修改剪切板。看控制台似乎有报错

![image](https://user-images.githubusercontent.com/18511905/175306450-1c4231e2-c6ff-4e22-9199-23d6a626492d.png)

```
Failed to load resource: the server responded with a status of 404 (Not Found)
character_table.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
main.1a573c4b7f5f63e3.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'writeText')
    at i.copyID (main.1a573c4b7f5f63e3.js:1:753018)
    at HTMLButtonElement.<anonymous> (main.1a573c4b7f5f63e3.js:1:640868)
    at v.invokeTask (polyfills.2e675a6ddad7deb2.js:1:7189)
    at Object.onInvokeTask (main.1a573c4b7f5f63e3.js:1:101017)
    at v.invokeTask (polyfills.2e675a6ddad7deb2.js:1:7110)
    at M.runTask (polyfills.2e675a6ddad7deb2.js:1:2584)
    at p.invokeTask [as invoke] (polyfills.2e675a6ddad7deb2.js:1:8240)
    at Z (polyfills.2e675a6ddad7deb2.js:1:20759)
    at N (polyfills.2e675a6ddad7deb2.js:1:21052)
    at HTMLButtonElement.B (polyfills.2e675a6ddad7deb2.js:1:21318)
bM @ main.1a573c4b7f5f63e3.js:1
```

**Comment by Shawnsdaddy** [comment]
HTTP 网址关了
